name: 6000.0.46f1-standalone

on:
  pull_request_target:
    branches:
      - main
    types: [opened, synchronize, reopened]

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  editor-tests:
    # Allow all push runs.
    # For PRs, run only if the PR carries the 'ci-ok' label
    if: github.event_name == 'push' ||
        contains(github.event.pull_request.labels.*.name, 'ci-ok')

    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '6000.0.46f1'
      testMode: 'standalone'
    secrets: inherit